'use strict';
// Run against npm start: node tests/display.browser.cjs /path/to/playwright
const { chromium } = require(process.argv[2] || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(String(error)));
  page.on('dialog', dialog => dialog.accept().catch(() => {}));
  const saved = () => page.evaluate(() => JSON.parse(localStorage.getItem('trama-er-v1')));
  const openView = async () => { if (await page.locator('#display-menu').getAttribute('open') === null) await page.locator('#display-menu summary').click(); };
  const exportFile = async kind => {
    await page.locator('#export-menu summary').click();
    const downloading = kind === 'json' ? null : page.waitForEvent('download');
    await page.locator(`[data-export="${kind}"]`).click();
    if (kind !== 'json') return fs.readFile(await (await downloading).path());
    const jsonDownload = page.waitForEvent('download');
    await page.locator('#export-download').click();
    return fs.readFile(await (await jsonDownload).path());
  };
  try {
    await page.goto(process.argv[3] || 'http://127.0.0.1:4173');
    await page.locator('#restructure').click();
    const before = await saved(), defaultMarkup = await page.locator('#diagram-content').innerHTML();
    const geometry = before.derived.model;
    await openView();
    await page.locator('#cardinality-style').selectOption('uml');
    assert.equal(await page.locator('#diagram-content .cardinality:not(.cardinality-uml)').count(), 0);
    assert.ok(await page.locator('.cardinality-uml').count() > 0);
    assert.ok((await page.locator('.cardinality-uml').allTextContents()).every(s => s === '1' || s === 'N'));
    await page.locator('#cardinality-style').selectOption('both');
    await page.locator('#show-relationship-type').check();
    const after = await saved();
    assert.deepEqual(after.model, before.model);
    assert.deepEqual(after.derived, before.derived);
    assert.deepEqual(after.display, { cardinalityStyle: 'both', showRelationshipType: true });
    assert.equal(await page.locator('.relationship-type').count(), geometry.relationships.length);
    assert.equal(await page.locator('#derived-status').textContent(), 'Ristrutturazione aggiornata');
    await page.keyboard.press('Escape');
    await page.locator('#fit').click();
    await page.screenshot({ path: '/private/tmp/trama-er-display-desktop.png' });
    await page.reload();
    assert.deepEqual((await saved()).display, after.display);
    assert.equal(await page.locator('#cardinality-style').inputValue(), 'both');
    const svg = (await exportFile('svg')).toString();
    assert.match(svg, /UML N/); assert.match(svg, /relationship-type/); assert.match(svg, /fill:#245d85/);
    const png = await exportFile('png');
    assert.equal(png.subarray(1, 4).toString(), 'PNG');
    const exported = JSON.parse((await exportFile('json')).toString());
    assert.deepEqual(exported.display, after.display);
    assert.deepEqual(exported.relationships, before.model.relationships);
    assert.equal(exported.entities[0].display, undefined);
    const input = async payload => {
      await page.locator('#file-input').setInputFiles({ name: 'schema.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(payload)) });
      await page.waitForFunction(expected => JSON.stringify(JSON.parse(localStorage.getItem('trama-er-v1')).display) === JSON.stringify(expected), payload.display || { cardinalityStyle: 'university', showRelationshipType: false });
    };
    await openView();
    await page.locator('#cardinality-style').selectOption('university');
    await page.locator('#show-relationship-type').uncheck();
    assert.equal(await page.locator('#diagram-content').innerHTML(), defaultMarkup);
    await page.keyboard.press('Escape');
    await input(exported);
    assert.deepEqual((await saved()).display, after.display);
    await page.locator('#schema-stage').selectOption('restructured');
    assert.equal(await page.locator('.relationship-type').count(), geometry.relationships.length);
    await page.evaluate(() => window.dispatchEvent(new Event('beforeprint')));
    assert.equal(await page.locator('#diagram').getAttribute('viewBox'), await page.evaluate(() => { const b = ER.render(shownModel(), '', display).bounds; return `${b.x} ${b.y} ${b.w} ${b.h}`; }));
    await page.evaluate(() => window.dispatchEvent(new Event('afterprint')));
    await page.setViewportSize({ width: 390, height: 844 });
    await openView();
    const menu = await page.locator('.display-options').boundingBox();
    assert.ok(menu.x >= 0 && menu.x + menu.width <= 390);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: '/private/tmp/trama-er-display-mobile.png', fullPage: true });
    await page.keyboard.press('Escape');
    const legacy = { ...exported }; delete legacy.display;
    await input(legacy);
    assert.deepEqual((await saved()).display, { cardinalityStyle: 'university', showRelationshipType: false });
    await page.locator('#undo').click();
    assert.deepEqual((await saved()).display, after.display, 'Undo project replacement restores its display preferences');
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.locator('#text-tab').click();
    await page.locator('#schema-text').fill('TITOLO: Cliente e ordini\nENTITA: Cliente\n- id [ID]\nENTITA: Ordine\n- numero [ID]\nASSOCIAZIONE: effettua: Cliente [0,N] -> Ordine [1,1]');
    await page.locator('#generate-text').click();
    assert.deepEqual(await page.locator('.cardinality-uml').allTextContents(), ['UML 1', 'UML N']);
    await page.locator('#structure-tab').click();
    await page.locator('#toast').waitFor({ state: 'hidden' });
    await page.screenshot({ path: '/private/tmp/trama-er-display-example.png' });
    assert.deepEqual(errors, []);
    console.log('PASS: three modes, unchanged definitions/derived model, JSON roundtrip/legacy/undo, reload, SVG/PNG/print, mobile menu');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
