'use strict';
// node tests/exercises.browser.cjs /path/to/playwright [url]
const { chromium } = require(process.argv[2] || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  let accept = true;
  const errors = [];
  page.on('dialog', dialog => (accept ? dialog.accept() : dialog.dismiss()).catch(() => {}));
  page.on('pageerror', error => errors.push(String(error)));
  const saved = () => page.evaluate(() => JSON.parse(localStorage.getItem('trama-er-v1')));
  const openTrace = () => page.locator('#manage-statement').click();
  try {
    await page.goto(process.argv[3] || 'http://127.0.0.1:4173');
    const initial = await saved();
    assert.equal(initial.metadata.createdAt, null, 'No creation dates are invented for existing examples');
    assert.equal(await page.locator('#example-select option').count(), 5);
    await openTrace();
    await page.locator('#statement-text').fill('Ogni cliente può effettuare molti ordini.\n<script>alert("x")</script>');
    await page.locator('#statement-apply').click();
    const first = await saved();
    assert.ok(first.metadata.updatedAt, 'A saved trace updates the modification date');
    assert.deepEqual(first.model, initial.model);
    assert.equal(await page.locator('#statement-panel').isVisible(), true);
    assert.equal(await page.evaluate(() => $('statement-panel').previousElementSibling.id), 'restructure-report');
    assert.equal(await page.evaluate(() => $('statement-panel').nextElementSibling.id), 'canvas');
    const panelBox = await page.locator('#statement-panel').boundingBox(), canvasBox = await page.locator('#canvas').boundingBox();
    assert.equal(panelBox.width, canvasBox.width, 'The trace keeps the full diagram width');
    assert.ok(panelBox.y + panelBox.height <= canvasBox.y, 'The trace appears above the diagram');
    assert.equal(await page.locator('#statement-content script').count(), 0);
    assert.match(await page.locator('#statement-content').textContent(), /<script>/);
    await page.locator('#display-menu summary').click();
    await page.locator('[data-font-target="statement"][data-font-step="1"]').click();
    assert.equal(await page.locator('.statement-text').evaluate(text => getComputedStyle(text).fontSize), '15px');
    await page.locator('[data-font-target="statement"][data-font-step="-1"]').click();
    assert.equal(await page.locator('.statement-text').evaluate(text => getComputedStyle(text).fontSize), '14px');
    await page.locator('#font-statement').fill('24'); await page.locator('#font-statement').press('Tab');
    assert.equal(await page.locator('.statement-text').evaluate(text => getComputedStyle(text).fontSize), '24px');
    assert.equal((await saved()).display.fontSizes.statement, 24);
    assert.equal((await saved()).metadata.updatedAt, first.metadata.updatedAt, 'Changing fonts does not update the content modification date');
    assert.deepEqual((await saved()).model, initial.model, 'The trace font does not alter the diagram definition');
    await page.keyboard.press('Escape');
    await page.locator('#statement-panel summary').click();
    assert.equal(await page.locator('#statement-content').isVisible(), false);
    await page.locator('#statement-panel summary').click();
    await page.locator('#display-menu summary').click(); await page.locator('#show-statement').uncheck();
    assert.equal(await page.locator('#statement-panel').isVisible(), false);
    await page.locator('#show-statement').check();
    await page.keyboard.press('Escape');
    await page.locator('#new-project').click();
    const secondId = (await saved()).activeExerciseId;
    const created = (await saved()).metadata;
    assert.ok(created.createdAt && created.updatedAt);
    assert.equal(created.createdAt, created.updatedAt);
    await page.locator('#exercises-button').click();
    assert.equal(await page.locator('.exercise-row>div>small').evaluateAll(items => items.every(item => item.getBoundingClientRect().height <= parseFloat(getComputedStyle(item).lineHeight) + 1)), true, 'Exercise information fits on one line in the desktop dialog');
    const classes = page.locator(`[data-classes-exercise="${secondId}"]`), classForm = classes.locator('form');
    await classes.locator('summary').click();
    await classForm.locator('[name="className"]').fill('5a');
    await classForm.locator('[name="schoolYear"]').fill('2026/27');
    await classForm.locator('button[type="submit"]').click();
    assert.deepEqual((await saved()).metadata.classTags, [{ className: '5A', schoolYear: '2026/27' }]);
    assert.equal((await saved()).metadata.createdAt, created.createdAt);
    await classForm.locator('[name="className"]').fill('5A');
    await classForm.locator('[name="schoolYear"]').fill('2026/27');
    await classForm.locator('button[type="submit"]').click();
    await page.locator('#exercises-error').waitFor({ state: 'visible' });
    assert.equal((await saved()).metadata.classTags.length, 1, 'Duplicate class/year tags are rejected');
    await classForm.locator('[name="schoolYear"]').fill('2027/28');
    await classForm.locator('button[type="submit"]').click();
    assert.equal((await saved()).metadata.classTags.length, 2, 'The same class can be used in distinct school years');
    const tagKey = JSON.stringify({ className: '5A', schoolYear: '2026/27' });
    const tagged = (await saved()).metadata;
    await page.locator('#exercise-class-filter').selectOption(tagKey);
    assert.equal(await page.locator('[data-open-exercise]').count(), 1);
    assert.equal(await page.locator(`[data-open-exercise="${secondId}"]`).count(), 1);
    assert.deepEqual((await saved()).metadata, tagged, 'Filtering does not modify an exercise');
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.locator('#exercises-dialog').evaluate(dialog => dialog.scrollWidth <= dialog.clientWidth), true, 'Expanded class/year controls fit on mobile');
    await page.screenshot({ path: '/private/tmp/trama-exercise-tags-mobile.png' });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.locator(`[data-exercise="${secondId}"][data-remove-class="0"]`).click();
    assert.equal((await saved()).metadata.classTags.length, 1);
    assert.equal(await page.locator('#exercise-class-filter').inputValue(), '', 'Removing the last occurrence clears the obsolete filter');
    await page.locator('#exercises-close').click();
    await page.locator('#project-title').fill('Secondo esercizio'); await page.locator('#project-title').press('Tab');
    await openTrace();
    await page.locator('#statement-file').setInputFiles({ name: 'traccia.txt', mimeType: 'text/plain', buffer: Buffer.from('Una farmacia vende medicinali.') });
    await page.waitForFunction(() => document.querySelector('#statement-file-name').textContent.includes('traccia.txt'));
    await page.locator('#statement-apply').click();
    assert.equal(await page.locator('.statement-text').evaluate(text => getComputedStyle(text).fontSize), '14px', 'A new exercise starts with the default trace font');
    await page.locator('#display-menu summary').click();
    await page.locator('#font-statement').fill('18'); await page.locator('#font-statement').press('Tab');
    await page.keyboard.press('Escape');
    await page.locator('#text-tab').click(); await page.locator('#schema-text').fill('ENTITA: Farmacia\n- id [ID]');
    await page.locator('#example-select').selectOption(initial.activeExerciseId);
    assert.equal((await saved()).statement.content, first.statement.content);
    assert.equal(await page.locator('.statement-text').evaluate(text => getComputedStyle(text).fontSize), '24px', 'Switching exercises restores the trace font');
    await page.locator('#example-select').selectOption(secondId);
    assert.equal(await page.locator('#schema-text').inputValue(), 'ENTITA: Farmacia\n- id [ID]');
    assert.equal((await saved()).statement.name, 'traccia.txt');
    await page.locator('#text-tab').click(); await page.locator('#generate-text').click(); await page.locator('#structure-tab').click();
    await page.reload();
    assert.equal((await saved()).activeExerciseId, secondId);
    assert.equal(await page.locator('#statement-panel').isVisible(), true);
    assert.equal(await page.locator('.statement-text').evaluate(text => getComputedStyle(text).fontSize), '18px', 'The trace font survives reload');
    assert.equal((await saved()).model.entities[0].name, 'Farmacia');
    await page.locator('#text-tab').click(); await page.locator('#schema-text').fill(''); await page.reload();
    assert.equal(await page.locator('#schema-text').inputValue(), '', 'An intentionally empty draft survives reload');
    await page.locator('#text-tab').click(); await page.locator('#schema-text').fill('ENTITA: Farmacia\n- id [ID]'); await page.locator('#structure-tab').click();
    await page.locator('#export-menu summary').click(); await page.locator('[data-export="json"]').click();
    const downloading = page.waitForEvent('download'); await page.locator('#export-download').click();
    const exported = JSON.parse(await fs.readFile(await (await downloading).path(), 'utf8'));
    assert.equal(exported.statement.content, 'Una farmacia vende medicinali.');
    assert.equal(exported.display.fontSizes.statement, 18);
    assert.equal(exported.metadata.createdAt, created.createdAt);
    assert.deepEqual(exported.metadata.classTags, [{ className: '5A', schoolYear: '2027/28' }]);
    await page.locator('#file-input').setInputFiles({ name: 'esercizio.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(exported)) });
    await page.waitForFunction(id => JSON.parse(localStorage.getItem('trama-er-v1')).activeExerciseId !== id, secondId);
    assert.deepEqual((await saved()).metadata, exported.metadata, 'JSON import preserves original dates and class tags');
    await page.locator('#example-select').selectOption(secondId);
    assert.deepEqual((await saved()).metadata, exported.metadata, 'Reopening a saved exercise does not change its dates');
    const beforeInvalid = await saved();
    await page.locator('#file-input').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ ...exported, statement: { name: 'x', type: 'text/html', content: '<script>x</script>' } })) });
    await page.waitForFunction(() => document.querySelector('#toast').textContent.includes('Impossibile aprire'));
    assert.deepEqual(await saved(), beforeInvalid);
    await openTrace();
    const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j/ZkAAAAASUVORK5CYII=', 'base64');
    await page.locator('#statement-file').setInputFiles({ name: 'traccia.png', mimeType: 'image/png', buffer: png });
    await page.waitForFunction(() => document.querySelector('#statement-file-name').textContent.includes('traccia.png'));
    await page.locator('#statement-apply').click();
    assert.equal(await page.locator('#statement-content img').count(), 1);
    await openTrace();
    await page.locator('#statement-file').setInputFiles({ name: 'fake.pdf', mimeType: 'application/pdf', buffer: Buffer.from('<html>fake</html>') });
    await page.locator('#statement-error').waitFor({ state: 'visible' });
    await page.locator('#statement-close').click();
    assert.equal((await saved()).statement.name, 'traccia.png');
    await openTrace();
    const pdf = '%PDF-1.4\n1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n2 0 obj\n<< /Type /Pages /Kids [] /Count 0 >>\nendobj\ntrailer\n<< /Root 1 0 R >>\n%%EOF';
    await page.locator('#statement-file').setInputFiles({ name: 'traccia.pdf', mimeType: 'application/pdf', buffer: Buffer.from(pdf) });
    await page.waitForFunction(() => document.querySelector('#statement-file-name').textContent.includes('traccia.pdf'));
    await page.locator('#statement-apply').click();
    assert.equal(await page.locator('#statement-content iframe').count(), 1);
    await page.locator('#exercises-button').click();
    accept = false; await page.locator('[data-delete-exercise="school"]').click(); accept = true;
    assert.equal(await page.locator('[data-open-exercise="school"]').count(), 1);
    await page.locator('[data-delete-exercise="school"]').click();
    assert.equal(await page.locator('[data-open-exercise="school"]').count(), 0);
    await page.locator('#restore-exercise').click();
    assert.equal(await page.locator('[data-open-exercise="school"]').count(), 1);
    await page.locator('[data-delete-exercise="school"]').click();
    await page.locator('#exercises-close').click(); await page.reload();
    assert.equal(await page.locator('#example-select option[value="school"]').count(), 0);
    await page.locator('#exercises-button').click(); await page.locator(`[data-delete-exercise="${secondId}"]`).click();
    assert.notEqual((await saved()).activeExerciseId, secondId);
    assert.equal(await page.locator(`[data-open-exercise="${secondId}"]`).count(), 0);
    await page.locator('#restore-exercise').click(); await page.locator(`[data-open-exercise="${secondId}"]`).click();
    assert.equal((await saved()).statement.name, 'traccia.pdf');
    await page.locator('#restructure').click();
    await openTrace(); await page.locator('#statement-text').fill('Progetta una base di dati per una farmacia.\n' + 'Ogni medicinale è prodotto da una ditta e può avere più utilizzi.\n'.repeat(80)); await page.locator('#statement-apply').click();
    const checkScroll = async () => {
      const metrics = await page.locator('#statement-body').evaluate(body => ({ height: body.getBoundingClientRect().height, max: Math.min(200, innerHeight / 4), scroll: body.scrollHeight, client: body.clientHeight }));
      assert.ok(metrics.height <= metrics.max);
      assert.ok(metrics.scroll > metrics.client, 'Long trace text scrolls inside the limited box');
      await page.locator('#statement-body').evaluate(body => { body.scrollTop = 40; });
      assert.ok(await page.locator('#statement-body').evaluate(body => body.scrollTop > 0));
    };
    await checkScroll();
    const beforeResize = await saved(), diagramWidth = (await page.locator('#canvas').boundingBox()).width;
    const handle = await page.locator('#statement-resize').boundingBox();
    await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2);
    await page.mouse.down();
    await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2 - 70, { steps: 5 });
    await page.mouse.up();
    assert.equal((await saved()).display.statementHeight, 130);
    assert.equal((await page.locator('#statement-body').boundingBox()).height, 130);
    assert.equal((await page.locator('#canvas').boundingBox()).width, diagramWidth);
    assert.deepEqual((await saved()).model, beforeResize.model, 'Resizing the trace preserves the diagram');
    assert.deepEqual((await saved()).statement, beforeResize.statement);
    await page.reload();
    assert.equal((await page.locator('#statement-body').boundingBox()).height, 130, 'The chosen height survives reload');
    await page.locator('#statement-resize').focus();
    await page.keyboard.press('ArrowUp');
    assert.equal((await saved()).display.statementHeight, 120);
    await page.keyboard.press('ArrowDown');
    assert.equal((await saved()).display.statementHeight, 130);
    await checkScroll();
    await page.locator('#display-menu summary').click();
    await page.locator('#font-nodes').fill('26'); await page.locator('#font-nodes').press('Tab');
    assert.equal((await saved()).display.statementHeight, 130, 'Font changes preserve the trace height');
    await page.keyboard.press('Escape');
    const erFonts = (await saved()).display.fontSizes;
    await page.locator('#schema-stage').selectOption('lab');
    assert.equal(await page.locator('#lab-panel').isVisible(), true);
    assert.equal(await page.locator('#statement-panel').isVisible(), true);
    assert.equal((await page.locator('#statement-body').boundingBox()).height, 130);
    await page.locator('#statement-panel summary').click();
    assert.equal(await page.locator('#statement-content').isVisible(), false);
    await page.locator('#statement-panel summary').click();
    await page.locator('#display-menu summary').click();
    assert.equal(await page.locator('#cardinality-style').isVisible(), false);
    assert.equal(await page.locator('#font-nodes').isVisible(), false);
    assert.equal(await page.locator('#font-statement').isVisible(), true);
    await page.locator('#show-statement').uncheck();
    assert.equal(await page.locator('#statement-panel').isVisible(), false);
    await page.locator('#show-statement').check();
    await page.locator('#font-statement').fill('22'); await page.locator('#font-statement').press('Tab');
    assert.equal(await page.locator('.statement-text').evaluate(text => getComputedStyle(text).fontSize), '22px');
    await page.locator('#reset-fonts').click();
    assert.deepEqual((await saved()).display.fontSizes, { ...erFonts, statement: 14 }, 'Reset in the lab only changes the trace font');
    await page.locator('#font-statement').fill('18'); await page.locator('#font-statement').press('Tab');
    await page.keyboard.press('Escape');
    await page.locator('#statement-resize').focus(); await page.keyboard.press('ArrowUp');
    assert.equal((await saved()).display.statementHeight, 120);
    await page.reload();
    assert.equal(await page.locator('#schema-stage').inputValue(), 'lab');
    assert.equal(await page.locator('#statement-panel').isVisible(), true);
    assert.equal((await page.locator('#statement-body').boundingBox()).height, 120);
    await page.screenshot({ path: '/private/tmp/trama-lab-trace-desktop.png' });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: '/private/tmp/trama-lab-trace-mobile.png', fullPage: true });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.locator('#schema-stage').selectOption('restructured');
    const openHeight = (await page.locator('#canvas').boundingBox()).height;
    await page.locator('#statement-panel summary').click();
    await page.waitForFunction(height => $('canvas').getBoundingClientRect().height > height, openHeight);
    assert.equal(await page.locator('#statement-content').isVisible(), false);
    await page.locator('#auto-layout').click();
    assert.equal(await page.locator('#statement-panel').getAttribute('open'), null, 'Redrawing preserves the collapsed trace');
    await page.locator('#statement-panel summary').click();
    await page.locator('#toast').waitFor({ state: 'hidden' });
    await page.screenshot({ path: '/private/tmp/trama-exercises-trace-desktop.png' });
    await page.setViewportSize({ width: 390, height: 844 }); await page.locator('#fit').click();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    assert.ok((await page.locator('#canvas').boundingBox()).height >= 180);
    await checkScroll();
    await page.locator('#statement-resize').focus(); await page.keyboard.press('Home');
    assert.equal((await page.locator('#statement-body').boundingBox()).height, 48);
    await page.keyboard.press('ArrowUp');
    assert.equal((await saved()).display.statementHeight, 48);
    await page.keyboard.press('End');
    assert.equal((await saved()).display.statementHeight, 200);
    await page.screenshot({ path: '/private/tmp/trama-exercises-trace-mobile.png', fullPage: true });
    await page.locator('#exercises-button').click();
    await page.screenshot({ path: '/private/tmp/trama-exercises-list-mobile.png' });
    await page.locator('#exercises-close').click();
    await openTrace(); await page.locator('#statement-remove').click();
    assert.equal((await saved()).statement, null);
    await page.locator('#undo').click(); assert.equal((await saved()).statement.type, 'text/plain');
    await page.locator('#exercises-button').click();
    while (await page.locator('[data-delete-exercise]').count()) await page.locator('[data-delete-exercise]').first().click();
    await page.reload();
    assert.equal(await page.locator('#example-select option').count(), 1, 'Deleted examples do not reappear when the library is empty');
    await page.locator('#new-project').click();
    const beforeQuota = await saved();
    await page.evaluate(() => { Storage.prototype.setItem = () => { throw new DOMException('Quota exceeded', 'QuotaExceededError'); }; });
    await page.locator('#exercises-button').click(); await page.locator('[data-delete-exercise]').first().click();
    await page.locator('#exercises-error').waitFor({ state: 'visible' });
    assert.deepEqual(await saved(), beforeQuota, 'A failed delete preserves the stored project and library');
    assert.equal(await page.locator('[data-open-exercise]').count(), 1, 'Failed deletion rolls back the visible library');
    assert.deepEqual(errors, []);
    console.log('PASS: library, built-in/active deletion, confirmation, restore, reload, per-exercise drafts/traces, JSON, TXT/image/PDF, rejected input, desktop/mobile');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
