'use strict';
// Run against npm start: node tests/relational-names.browser.cjs /path/to/playwright [url]
const { chromium } = require(process.argv[2] || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(String(error)));
  page.on('dialog', dialog => dialog.accept().catch(() => {}));
  const saved = () => page.evaluate(() => JSON.parse(localStorage.getItem('trama-er-v1')));
  const edit = async (id, name) => {
    if (await page.locator('.relational-name-editor').getAttribute('open') === null) await page.locator('.relational-name-editor summary').click();
    await page.locator('#relational-name-table').selectOption(id);
    await page.locator('#relational-name').fill(name);
    await page.locator('#relational-name-form button').click();
  };
  const exportFile = async kind => {
    await page.locator('#export-menu summary').click();
    const downloading = kind === 'json' ? null : page.waitForEvent('download');
    await page.locator(`[data-export="${kind}"]`).click();
    if (downloading) return fs.readFile(await (await downloading).path(), 'utf8');
    const jsonDownload = page.waitForEvent('download');
    await page.locator('#export-download').click();
    return fs.readFile(await (await jsonDownload).path(), 'utf8');
  };
  try {
    await page.goto(process.argv[3] || 'http://127.0.0.1:4173');
    await page.locator('#text-tab').click();
    await page.locator('#schema-text').fill('TITOLO: Proprietari e auto\nENTITA: proprietario\n- id [ID]\n- cf\n- telefono [0,N]\nENTITA: auto\n- id [ID]\nASSOCIAZIONE: possiede: proprietario [1,N] -> auto [0,1]\nASSOCIAZIONE: usa: proprietario [0,N] -> auto [0,N]');
    await page.locator('#generate-text').click();
    await page.locator('#relational-generate').click();
    const initial = await saved(), owner = initial.derived.relational.tables.find(t => t.name === 'proprietari');
    await edit(owner.id, 'titolari');
    let record = await saved();
    assert.deepEqual(record.model, initial.model);
    assert.deepEqual(record.derived.model, initial.derived.model);
    assert.equal(record.derived.relational.tables.find(t => t.id === owner.id).name, 'titolari');
    assert.deepEqual(record.derived.relational.tables.map(({ name, ...structure }) => structure), initial.derived.relational.tables.map(({ name, ...structure }) => structure));
    assert.match(await page.locator('#relational-compact').textContent(), /titolari/);
    assert.match(await exportFile('relational'), /-> titolari\(id\)/);
    await page.locator('#undo').click();
    assert.equal((await saved()).derived.relational.tables.find(t => t.id === owner.id).name, 'proprietari');
    await page.locator('#redo').click();
    await page.reload();
    assert.equal((await saved()).derived.relational.tables.find(t => t.id === owner.id).name, 'titolari');
    const beforeInvalid = await saved();
    await edit(owner.id, 'AUTO');
    await page.locator('#relational-name-error').waitFor({ state: 'visible' });
    assert.deepEqual(await saved(), beforeInvalid, 'Duplicate names do not alter the saved schema');
    await edit(owner.id, '   ');
    await page.locator('#relational-name-error').waitFor({ state: 'visible' });
    assert.deepEqual(await saved(), beforeInvalid);
    const phone = beforeInvalid.derived.relational.tables.find(t => t.name.includes('telefon'));
    await edit(phone.id, 'recapiti');
    await page.locator('#restructure').click();
    await page.locator('#relational-generate').click();
    record = await saved();
    assert.ok(record.derived.relational.tables.some(t => t.name === 'recapiti'), 'Extracted relation aliases survive new generated node IDs');
    assert.ok(record.derived.relational.tables.some(t => t.name === 'titolari'));
    await page.locator('#relational-view').selectOption('tables');
    assert.match(await page.locator('#relational-tables').textContent(), /titolari/);
    await page.locator('#physical-generate').click();
    await page.locator('#physical-table').selectOption(owner.id);
    assert.equal(await page.locator('#physical-quote-identifiers').isChecked(), true);
    await page.locator('#physical-quote-identifiers').uncheck();
    await page.locator('#physical-form button[type="submit"]').first().click();
    assert.equal((await saved()).derived.physical.quoteIdentifiers, false);
    assert.doesNotMatch(await page.locator('#physical-sql').inputValue(), /`/);
    await page.locator('[data-sql-action="download"]').click();
    const sqlDownload = page.waitForEvent('download');
    await page.locator('#export-download').click();
    assert.doesNotMatch(await fs.readFile(await (await sqlDownload).path(), 'utf8'), /`/);
    await page.reload();
    assert.equal(await page.locator('#physical-quote-identifiers').isChecked(), false);
    const unquoted = await saved();
    await page.locator('#physical-table-name').fill('nome con spazi');
    await page.locator('#physical-form button[type="submit"]').first().click();
    await page.locator('#physical-error').waitFor({ state: 'visible' });
    assert.deepEqual(await saved(), unquoted, 'Invalid unquoted names leave the applied project intact');
    await page.locator('#physical-table-name').fill('titolari');
    await page.locator('#physical-quote-identifiers').check();
    await page.locator('#physical-form button[type="submit"]').first().click();
    assert.match(await page.locator('#physical-sql').inputValue(), /CREATE TABLE IF NOT EXISTS `titolari`/);
    const cfIndex = (await saved()).derived.physical.tables.find(t => t.id === owner.id).columns.findIndex(c => c.name === 'cf');
    await page.locator(`#sql-type-${cfIndex}`).fill('CHAR(16)');
    await page.locator('#physical-checks').fill("cf <> ''");
    await page.locator('#physical-include-engine').check();
    await page.locator('#physical-form button[type="submit"]').last().click();
    const applied = await saved();
    assert.equal(applied.derived.physical.tables.find(t => t.id === owner.id).columns[cfIndex].type, 'CHAR(16)');
    await page.locator('#schema-stage').selectOption('relational');
    await edit(owner.id, 'Proprietari corretti');
    record = await saved();
    assert.deepEqual(record.derived.physical.tables.map(t => ({ ...t, name: t.id === owner.id ? 'titolari' : t.name })), applied.derived.physical.tables, 'Renaming preserves all applied SQL options');
    assert.equal(record.derived.physical.tables.find(t => t.id === owner.id).name, 'proprietari corretti');
    await page.locator('#physical-generate').click();
    assert.match(await page.locator('#physical-sql').inputValue(), /REFERENCES `proprietari corretti`/);
    await page.locator('#schema-stage').selectOption('relational');
    const exported = JSON.parse(await exportFile('json'));
    assert.equal(exported.derived.relational.nameOverrides[owner.id], 'Proprietari corretti');
    const beforeImportId = (await saved()).activeExerciseId;
    await page.locator('#file-input').setInputFiles({ name: 'nomi.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(exported)) });
    await page.waitForFunction(id => JSON.parse(localStorage.getItem('trama-er-v1')).activeExerciseId !== id, beforeImportId);
    await page.locator('#schema-stage').selectOption('relational');
    assert.equal((await saved()).derived.relational.tables.find(t => t.id === owner.id).name, 'Proprietari corretti');
    const importedId = (await saved()).activeExerciseId;
    await page.locator('#example-select').selectOption(initial.activeExerciseId);
    assert.equal((await saved()).derived.relational.tables.find(t => t.id === owner.id).name, 'Proprietari corretti');
    await page.locator('#example-select').selectOption(importedId);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.locator('.relational-name-editor summary').click();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: '/private/tmp/trama-relational-names-mobile.png', fullPage: true });
    assert.deepEqual(errors, []);
    console.log('PASS: manual names, duplicate/empty rejection, unchanged ER/keys, undo, reload, regeneration, SQL options/FKs, export/import, exercises and mobile');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
